<a href="https://colab.research.google.com/github/Selami7321/Python-ile-Makine-Ogrenmesi/blob/main/Naive_Byes_ile_S%C4%B1n%C4%B1fland%C4%B1rma_ile_S%C4%B1n%C4%B1fland%C4%B1rma_ipynb_adl%C4%B1_not_defterinin_kopyas%C4%B1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:

#1.kutuphaneler
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#2.veri onisleme
#2.1.veri yukleme
veriler = pd.read_csv('veriler.csv')
#pd.read_csv("veriler.csv")
#test
print(veriler)

x= veriler.iloc[ : , 2:4 ].values # bağımsız değişkenler
y= veriler.iloc [: , 4:].values # Bağımlı değişkenler


#verilerin egitim ve test icin bolunmesi
from sklearn.model_selection import train_test_split

x_train, x_test,y_train,y_test = train_test_split(x,y,test_size=0.33, random_state=0)

#verilerin olceklenmesi
from sklearn.preprocessing import StandardScaler

sc=StandardScaler()

X_train = sc.fit_transform(x_train)
X_test = sc.transform(x_test)


#-------------------------------
# Sınıflandırmaya Başlayalım
from sklearn.linear_model import LogisticRegression
Logreg=LogisticRegression(random_state=0)
Logreg.fit(X_train,y_train)
y_pred=Logreg.predict(X_test)
print(y_pred)
print(y_test)


#Confusion Matrisi -  Karışıklık Matrisi
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
print(cm)


#KNN  Algoritması
from sklearn.neighbors import KNeighborsClassifier
# Burada n_neighbors değerini yüksek tutmamın sebebi klasik düşünce olan verisetinin ne kadar çok veriyle eğitilirse sonuçları o kadar iyi tahmin eder yaklaşımını kırmakm için bunu belirtmek istedim verileri azaltarak doğruluk değerimizin komşu değerlere bağlı olduğunu veri sayısına bağlı olmadığını göstermek istedim

knnAlgoritm=KNeighborsClassifier(n_neighbors=7,metric="minkowski")
knnAlgoritm.fit(X_train,y_train)
y_pred=knnAlgoritm.predict(X_test)
cm= confusion_matrix(y_test,y_pred)
print(cm)

knnAlgoritm=KNeighborsClassifier(n_neighbors=1,metric="minkowski")
knnAlgoritm.fit(X_train,y_train)
y_pred=knnAlgoritm.predict(X_test)

cm= confusion_matrix(y_test,y_pred)
print(" KNN Algoritm ")
print(cm)


#-------------------------
# Naive Byes  Gaussian Naive Bayes

from sklearn.naive_bayes import GaussianNB
gnb=GaussianNB()
gnb.fit(X_train,y_train)
y_pred=gnb.predict(X_test)
cm= confusion_matrix(y_test,y_pred)
print("Gaussion Naive Bayes ")
print(cm)


from sklearn.naive_bayes import BernoulliNB
bnb=BernoulliNB()
bnb.fit(X_train,y_train)
y_pred=bnb.predict(X_test)

cm= confusion_matrix(y_test,y_pred)
print("Bernoulli Naive Bayes")
print(cm)


   ulke  boy  kilo  yas cinsiyet
0    tr  130    30   10        e
1    tr  125    36   11        e
2    tr  135    34   10        k
3    tr  133    30    9        k
4    tr  129    38   12        e
5    tr  180    90   30        e
6    tr  190    80   25        e
7    tr  175    90   35        e
8    tr  177    60   22        k
9    us  185   105   33        e
10   us  165    55   27        k
11   us  155    50   44        k
12   us  160    58   39        k
13   us  162    59   41        k
14   us  167    62   55        k
15   fr  174    70   47        e
16   fr  193    90   23        e
17   fr  187    80   27        e
18   fr  183    88   28        e
19   fr  159    40   29        k
20   fr  164    66   32        k
21   fr  166    56   42        k
['e' 'e' 'e' 'e' 'k' 'e' 'e' 'k']
[['k']
 ['k']
 ['k']
 ['k']
 ['e']
 ['k']
 ['k']
 ['k']]
[[0 1]
 [6 1]]
[[1 0]
 [7 0]]
 KNN Algoritm 
[[1 0]
 [1 6]]
Gaussion Naive Bayes 
[[0 1]
 [6 1]]
Bernoulli Naive Bayes
[[0 1]
 [7 0]]


/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.11/dist-packages/sklearn/neighbors/_classification.py:239: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
/usr/local/lib/python3.11/dist-packages/sklearn/neighbors/_classification.py:239: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for exampl